### Example configuration for Circle CI ###

version: 2

# Note that CircleCI's support for multiple jobs with the same steps is nonexistant.
# So, each implementation needs an entry in the jobs group, and to be listed in the workflows section at the bottom.

jobs:
  sbcl-build:
    environment:
      LISP: sbcl-bin
      VERSION: 2.3.0
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          echo $LISP && \
          curl -L https://raw.githubusercontent.com/roswell/roswell \/release/scripts/install-for-ci.sh | bash
          ros install sbcl-bin/2.3.0 && \
          ros use sbcl-bin/2.3.0 && \
          ros install neil-lindquist/ci-utils # for run-fiveam
      - run: make build
      - run: mv cl-fzy build/
      - store_artifacts:
          path: build/
  sbcl-test:
    docker:
      - image: circleci/buildpack-deps:stretch-curl
    environment:
      LISP: sbcl-bin
    steps:
      - checkout
      # This is the only way CircleCI allows setting environmental variables accross steps
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$HOME/.roswell/bin:$PATH" >> $BASH_ENV

      - run: echo $LISP
      - run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | bash
      - run: ros install sbcl-bin/2.3.0
      - run: ros use sbcl-bin/2.3.0
      - run: ros install neil-lindquist/ci-utils # for run-fiveam

      - run: run-fiveam -e t -l cl-fzy-tests :cl-fzy-tests
      #- run: run-prove foo.asd
      #- run: rove foo.asd

workflows:
  version: 2
  run_tests:
    jobs:
      - sbcl-test
      - sbcl-build